### ISSUE TITLE
Not working on my site

### ISSUE THREAD

**Issue by teleyinex** [thoughtbot/carnival#265]
Hi,

I've just deployed it on my site and nothing is shown. The DOM is populated correctly, but I cannot see it. Could it be something related to the CSS?

This is the page where I've deployed it: http://daniellombrana.es/blog/2015/03/05/uwsgi.html

**Comment by jferris** [comment]
@teleyinex thanks for trying out Carnival.

It looks like there's a `overflow: hidden` on your `section` elements that's hiding the Carnival comment indicators.

Our default styles are intended to work and look good out of the box, but that isn't possible on every page due to the wide variety of visual styles and techniques for implementing them.

Removing the `overflow: hidden` should get you started. You can target `.carnval` and `.carnival-comment-indicator` to customize the appearance of the indicators and comments.

We're still experimenting with the best default styles, so these may vary over time.

Let me know if you need any more help getting things working.

**Comment by teleyinex** [comment]
@jferris Thanks! I've just fixed it and now is working (I've even customized a bit the look and feel for better integration in my site).

**Comment by jferris** [comment]
@teleyinex awesome! Please let us know if you have any thoughts or questions about Carnival.

**Comment by teleyinex** [comment]
Sure! I'll do. I would love to recommend you on Product Hunt but I can't as I don't have an invite. If you have one, I would be happy to comment on your page ;-)
