### ISSUE TITLE
Official tutorial for VPS

### ISSUE THREAD

**Issue by aixnr** [thoughtbot/carnival#271]
As of now the official tutorial only available for Heroku. Wonder if you guys can write an official documentation on how to deploy Carnival on VPS, say, a DigitalOcean droplet.

**Comment by jferris** [comment]
Hey @aixnr,

I think you're talking about the documentation here: https://github.com/thoughtbot/carnival/blob/master/DEPLOYMENT.md

This is our documentation on how we deploy Carnival, and we use Heroku.

We've decided to open source Carnival because:

* We believe in transparency and openness
* We want to assure our users that we have no intention of locking them in
* We want to promote and showcase our work in Haskell

We're also running it as a paid service at https://carnivalapp.io/. We recommend that you sign up on our site instead of trying to run it yourself. It's free for small, personal sites and will definitely be easier.

There's nothing stopping you from deploying it yourself, to Heroku or elsewhere. However, that's not what we recommend and it's not something we want to dedicate resources to right now.

Thanks for checking out Carnival!
